// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvS-fBKUrwj1sop6kFptfh0971RI6JFFU',
    appId: '1:252987087956:web:c95bc761dbc2056a5aa1c1',
    messagingSenderId: '252987087956',
    projectId: 'uexpense2',
    authDomain: 'uexpense2.firebaseapp.com',
    storageBucket: 'uexpense2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi0D3fvcI8y2GlQQl41vLLhu0Qdzno790',
    appId: '1:252987087956:android:c24ee03c85989cb35aa1c1',
    messagingSenderId: '252987087956',
    projectId: 'uexpense2',
    storageBucket: 'uexpense2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4Wm9WgzpqBWekinxjvuv6pIoeNrC1wD4',
    appId: '1:252987087956:ios:d464d4157bb2d5dd5aa1c1',
    messagingSenderId: '252987087956',
    projectId: 'uexpense2',
    storageBucket: 'uexpense2.appspot.com',
    iosBundleId: 'com.example.myfirstapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4Wm9WgzpqBWekinxjvuv6pIoeNrC1wD4',
    appId: '1:252987087956:ios:d464d4157bb2d5dd5aa1c1',
    messagingSenderId: '252987087956',
    projectId: 'uexpense2',
    storageBucket: 'uexpense2.appspot.com',
    iosBundleId: 'com.example.myfirstapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvS-fBKUrwj1sop6kFptfh0971RI6JFFU',
    appId: '1:252987087956:web:b279c64aeff228bc5aa1c1',
    messagingSenderId: '252987087956',
    projectId: 'uexpense2',
    authDomain: 'uexpense2.firebaseapp.com',
    storageBucket: 'uexpense2.appspot.com',
  );
}
